stages:
  - build

frontend-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - docker login -u "$registryuser" -p "$registrypass" $registryurl
    - docker build --tag $registryurl/collegegram/frontend:${CI_COMMIT_SHA:0:8} ./
    - docker tag $registryurl/collegegram/frontend:${CI_COMMIT_SHA:0:8} $registryurl/collegegram/frontend:latest
    - docker push $registryurl/collegegram/frontend:latest
    - ssh root@$prodserver "cd ~; docker-compose pull; docker-compose up -d; docker exec nginx nginx -s reload"
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'